name: API CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.17.1
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Functions Lint
        run: pnpm --filter @maru/functions lint --if-present
