name: Web CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9.6.0 }
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Typecheck & Build
        run: |
          pnpm prisma:generate
          pnpm --filter @maru/web build
